### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by amakly** [NESREA/webreport#16]
ERROR: this R is version 3.2.3, package 'webreport' requires R >= 3.4.3
Error: Command failed (1)

**Comment by BroVic** [comment]
You need to update R to the current version. The package depends on versions of R not lower than **3.4.3** - the version you have is **3.2.3**!

***You should use R GUI (not R Studio) to perform these tasks***

There are many ways install/update R but this method is recommended:
Get the install the ` installr ` package if you don't already have it (I bet you don't)
```
install.packages(pkgs = "installr")
```
Once the package is installed, you can load it with
```
library(installr)
```
Not the difference between these 2 functions; in the first, the `installr` argument is quoted and in the second it is not.

The next step is to update your R installation by simply running
```
uptateR()
```
You will get some prompts, which after you have clicked through the new R version will be installed.

**Comment by BroVic** [comment]
@amakly 
I have this R package I wrote for personal convenience that you can take advantage of to easily update your R installation. 

Run the following lines of code one after the other:
```
devtools::install_github("BroVic/myRstuff")
library(myRstuff)
install_R_my_way()
```

That's all. See you on the other side.
